const data = {
  products: [
    {
      name: "React shirt",
      slug: "react-shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Next JS shirt",
      slug: "nextjs-shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 80,
      brand: "Adidas",
      rating: 3.5,
      numReviews: 8,
      countInStock: 3,
      description: "A popular shirt",
    },
    {
      name: "Github shirt",
      slug: "github-shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 50,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 5,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 60,
      brand: "Oliver",
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: "Smart looking pants",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 75,
      brand: "Zara",
      rating: 2.5,
      numReviews: 18,
      countInStock: 20,
      description: "Smart looking pants",
    },
    {
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 80,
      brand: "Casely",
      rating: 4.0,
      numReviews: 3,
      countInStock: 100,
      description: "Smart looking pants",
    },
  ],
};

export default data;
